version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  
- package-ecosystem: npm
  directory: "/near-workspaces/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
